In [3]:
import psycopg2 # драйвер для postgresql
import getpass  # прячем параль, чтобы не писать его в параметрах

conn=psycopg2.connect(user='postgres',
                      database='HW',
                      host='localhost',
                      port='5432',
                      password=getpass.getpass('Insert password: ')
                        )

Insert password: ········

In [7]:
query = """ SELECT *
            FROM (SELECT MAX("CPN") AS "CPN", "ISIN", max("BUYBACKDATE") AS "BUYBACKDATE",
                  max("BUYBACKPRICE") AS "BUYBACKPRICE"
                  FROM public.quotes_task
                  GROUP BY "ISIN") AS cpn
            INNER JOIN(SELECT "ISINCode", "FaceValue", "HaveOffer", "AmortisedMty", 
                       "CouponPerYear", "NumCoupons", "EndMtyDate", "CouponType", "IssuerName"
                       FROM public.bond_description_task
                       WHERE "Status"!='Погашен') AS bonds
            ON cpn."ISIN" = bonds."ISINCode" """

In [6]:
import pandas as pd
data = pd.read_sql_query(query, conn)
data = pd.DataFrame(data)
data = data.drop(['ISINCode'], axis=1)
data.head(10)

,CPN,ISIN,BUYBACKDATE,BUYBACKPRICE,FaceValue,HaveOffer,AmortisedMty,CouponPerYear,NumCoupons,EndMtyDate,CouponType,IssuerName
0,97.50,RU000A0JRYJ0,None,NaN,1000.0,False,False,2,9,2016-11-29,Постоянный,Автодор ГК
1,24.56,RU000A0JTG34,None,NaN,1000.0,False,True,4,20,2017-12-17,Постоянный,Воронежская Обл Прав
2,20.64,RU000A0JU823,None,NaN,1000.0,False,True,4,20,2018-10-23,Фиксированный,Воронежская Обл Прав
3,29.29,RU000A0JUWK6,None,NaN,1000.0,False,True,4,20,2019-10-14,Постоянный,Воронежская Обл Прав
4,26.55,RU000A0JS1E8,None,NaN,1000.0,False,True,4,20,2016-12-14,Постоянный,Вологодская Обл Прав
5,24.31,RU000A0JTF68,None,NaN,1000.0,False,True,4,20,2017-12-05,Постоянный,Вологодская Обл Прав
6,51.37,RU000A0JV3M2,None,NaN,1000.0,False,True,4,20,2019-12-24,Постоянный,Волжский Адм
7,39.89,RU000A0JRGR0,None,NaN,1000.0,False,True,2,10,2016-05-04,Фиксированный,Волгоградская Обл Адм
8,26.80,RU000A0JUP89,None,NaN,1000.0,False,True,4,20,2019-07-13,Фиксированный,Волгоградская Обл Адм
9,34.76,RU000A0JUWU5,None,NaN,1000.0,False,True,4,20,2019-10-10,Фиксированный,Волгоград Адм